private_diary/diary/urls.py
from django.urls import path

from . import views

app_name = "diary"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("inquiry/", views.InquiryView.as_view(), name="inquiry"),
    path('diary-list/', views.DiaryListView.as_view(), name="diary_list"),
]

private_diary/private_diary/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import static

from . import settings_common, settings_dev
urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("diary.urls")),
    path("accounts/", include('allauth.urls')),
]

# 開発サーバーでメディアを配信できるようにする設定
urlpatterns += static(settings_common.MEDIA_URL, document_root=settings_dev.MEDIA_ROOT)

private_diary/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    """拡張ユーザーモデル"""

    class Meta:
        verbose_name_plural = 'CustomUser'

private_diary/diary/models.py
from accounts.models import CustomUser
from django.db import models

class Diary(models.Model):
    # 日記モデル

    user = models.ForeignKey(CustomUser, verbose_name='ユーザー', on_delete=models.PROTECT)
    title = models.CharField(verbose_name='タイトル', max_length=40)
    content = models.CharField(verbose_name='本文', blank=True, null=True)
    photo1 = models.ImageField(verbose_name='写真１', blank=True,  null=True)
    photo2 = models.ImageField(verbose_name='写真２', blank=True,  null=True)
    photo3 = models.ImageField(verbose_name='写真３', blank=True,  null=True)
    created_date = models.DateTimeField(verbose_name='作成日時', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='更新日時', auto_now=True)


class Meta:
    verbose_name_plural = 'Diary'

    def __str__(self):
        return self.title

private_diary/diary/forms.py
import os 

from django import forms
from django.core.mail import EmailMessage


class InquiryForm(forms.Form):
    name = forms.CharField(label="お名前", max_length=30)
    email = forms.EmailField(label="メールアドレス")
    title = forms.CharField(label="タイトル", max_length=30)
    message = forms.CharField(label="メッセージ", widget=forms.Textarea)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields["name"].widget.attrs["class"] = "form-control"
        self.fields["name"].widget.attrs["placeholder"] = "お名前をここに入力してください"

        self.fields["email"].widget.attrs["class"] = "form-control"
        self.fields["email"].widget.attrs["placeholder"] = "メールアドレスをここに入力してください"

        self.fields["title"].widget.attrs["class"] = "form-control"
        self.fields["title"].widget.attrs["placeholder"] = "タイトルをここに入力してください"

        self.fields["message"].widget.attrs["class"] = "form-control"
        self.fields["message"].widget.attrs["placeholder"] = "メッセージをここに入力してください"

    def send_email(self):
        name = self.cleaned_data["name"]
        email = self.cleaned_data["email"]
        title = self.cleaned_data["title"]
        message = self.cleaned_data["message"]

        subject = "お問い合わせ {}".format(title)
        message = "送信者名: {0}\nメールアドレス {1}\nメッセージ {2}".format(name, email, message)
        from_email = os.environ.get("FROM_EMAIL")
        to_list = [
            os.environ.get("FROM_EMAIL")
        ]
        cc_list = [
            email
        ]

        message = EmailMessage(subject=subject, body=message, from_email=from_email, to=to_list, cc=cc_list)
        message.send()

private_diary/accounts/views.py
from django.shortcuts import render

# Create your views here.

private_diary/diary/views.py
import logging
from django.urls import reverse_lazy
from django.views import generic
from .forms import InquiryForm
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from . models import Diary

logger = logging.getLogger(__name__)


class IndexView(generic.TemplateView):  # ホーム画面
    template_name = "index.html"


class InquiryView(generic.FormView):  # 問い合わせ画面
    template_name = "inquiry.html"
    form_class = InquiryForm
    success_url = reverse_lazy("diary:inquiry")

    def form_valid(self, form):
        form.send_email()
        messages.success(self.request, 'メッセージを送信しました')
        logger.info("Inquiry sent by {}".format(form.cleaned_data["name"]))
        return super().form_valid(form)


class DiaryListView(LoginRequiredMixin, generic.ListView):  # 日記の一覧表示
    model = Diary
    template_name = 'diary_list.html'

    def get_queryset(self):
        diaries = Diary.objects.filter(user=self.request.user).order_by('-created_at')
        return diaries

private_diary/diary/templates/base.html
{% load static %}

<html lang="ja">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="">
        <title>{% block title %}{% endblock %}</title>
        <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}"/>             

        <!-- Font Awesome icons (free version) -->
        <script src="https://use.fontawesome.com/releases/v5.15.3/js/all.js" crossorigin="anonymous"></script>
        <!-- Google Fonts -->               
        <link href="https://fonts.googleapis.com/releases/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet"/>
        <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet"/>
        
        <!-- Core theme CSS(includes Bootstrap)-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet"/>
        <link href="{% static 'css/one-page-wonder.css' %}" rel="stylesheet"/>

        <!-- My style -->
        <link rel="stylesheet" type="text/css" href="{% static 'css/mystyle.css' %}">
        {% block head %}{% endblock %}
    </head>

    <body>
        <div id="wrapper">
            <!-- Navigation-->
            <nav class="navbar navbar-expand-lg navbar-dark navbar-custom fixed-top">
                <div class="container px-5">
                    <a class="navbar-brand" href="{% url 'diary:index' %}">PRIVATE DIARY</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link {% block active_inquiry %}{% endblock %}" href="{% url 'diary:inquiry' %}">INQUIRY</a>
                        </li>
                        {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'diary:diary_list' %}">Diary List</a>
                        </li>
                        {% endif %}
                    </ul>
                    <ul class="navbar-nav ms-auto">
                        {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'account_logout' %}">Log Out</a>
                        </li>
                        {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="#">Signup</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Log In</a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>

        {% block header %}{% endblock %}

        {% if messages %}
        <div class="container my-dev-style">
            <div class="row">
                <ul class="messages" style="list-style: none;">
                    {% for message in messages %}
                    <li {% if message.tags %}class="{{message.tags}}"{% endif %}>
                        {{message}}
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
        {% endif %}

        {% block contents %}{% endblock %}

        <!-- Footer -->
        <footer class="py-5 bg-black">
            <div class="container px-5">
                <p class="m-0 text-center text-white small">Copyright &copy; Private Diary 2024</p>
            </div>
        </footer>

        <!-- Bootstrap core js -->
         <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"></script>
        </div>
    </body>
</html>

private_diary/diary/templates/diary_list.html
{% extends "base.html" %}
{% load static %}

{% block title %}
  Diary List
{% endblock %}
{% block active_diary_list %}
    active
{% endblock %}
{% block head %}
  <link rel="stylesheet" href="{% static 'css/clean-blog.css' %}">
{% endblock %}

{% block content %}
<div class="container px-4 px-lg-5 my-div-style">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
            <div class="d-flex justify-content-end mb-4">
                <a class="btn btn-primary float-right" href="#">新規作成</a>
            </div>
            {% for diary in diary_list %}
            <div class="post-preview">
                <a href="#">
                    <h2 class="post-title">
                        {{ diary.title}}
                    </h2>
                    <h3 class="post-subtitle">
                        {{ diary.content|truncatewords:20 }}
                    </h3>
                </a>
                <p class="post-meta">{{ diary.created_at|date:"Y年m月d日 H:i" }}</p>
            </div>
            <hr class="my-4">
            <p>日記がありません</p>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

private_diary/diary/templates/index.html
{% extends "base.html" %}

{% load static %}

{% block title %}web上にあなた専用の日記を保存できるサービス|Private Diary{% endblock %}

{% block header %}

<header class="masthead text-center text-white">
    <div class="masthead-content">
        <div class="container">
            <h1 class="masthead-heading mb-0">Private Diary</h1>
            <h2 class="masthead-subheading mb-0">あなた専用の日記を作成する</h2>
            <a href="{% url 'account_login' %}" class="btn btn-primary btn-xl rounded-pill mt-5">LOG IN</a>
        </div>
    </div>
    <div class="bg-circle-1 bg-circle"></div>
    <div class="bg-circle-2 bg-circle"></div>
    <div class="bg-circle-3 bg-circle"></div>
    <div class="bg-circle-4 bg-circle"></div>
</header>
{% endblock %}

{% block contents %}
<section>
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-6 order-lg-2">
                <div class="p-5">
                    <img class="img-fluid rounded-circle" src="{% static 'assets/img/01.jpg' %}" alt="">
                </div>
            </div>
            <div class="col-lg-6 order-lg-1">
                <div class="p-5">
                    <h2 class="display-4">Web Diary</h2>
                    <p>Web上で作成/編集/削除が可能な日記サービスです。</p>
                </div>
            </div>
        </div>
    </div>
</section>

<section>
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-6">
                <div class="p-5">
                    <img class="img-fluid rounded-circle" src="{% static 'assets/img/02.jpg' %}" alt="">
                </div>
            </div>
            <div class="col-lg-6">
                <div class="p-5">
                <h2 class="display-4">Save your diary</h2>
                <p>あなたの日記をwebに保存</p>
                </div>
            </div>
        </div>
    </div>
</section>

<section>
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-6 order-lg-2">
                <div class="p-5">
                    <img class="img-fluid rounded-circle" src="{% static 'assets/img/03.jpg' %}" alt="">
                </div>
            </div>
            <div class="col-lg-6 order-lg-1">
                <div class="p-5">
                    <h2 class="display-4">MemberShip System</h2>
                    <p>会員登録を行うことで、あなたの日記をWeb上に保存できます。</p>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

private_diary/diary/templates/inquiry.html
{% extends "base.html" %}

{% block title %}お問い合わせ{% endblock %}

{% block active_inquiry %}active{% endblock %}

{% block contents %}
<div class="cotainer d-flex justify-content-center">
    <div class="my-div-style col-12 col-md-7">
        <form method="post">
            {% csrf_token %}

            {{ form.non_field_errors }}

            {% for field in form %}
            <div class="mb-4">
                <label for="{{ field.id_for_label }}" class="form-label">
                    <strong>{{ fields.label_tag }}</strong>
                </label>
                {{ field }}
                {{ field.errors }}
            </div>
            {% endfor %}
            <button class="btn btn-primary" type="submit">送信</button>
        </form>
    </div>
</div>
{% endblock %}